package com.calculator.mycalculator;

public class Help {
 public static String s=new StringBuilder()
 .append("<p>Thank you for chosing to download my aplication on your smart device. For any comment, idea or help please contact us throught our email address: calc4funhelp@gmail.com</p>")
 .append("<p><font color='red'><strong>PRIORITY LEVEL AND EXAMPLES:</strong></font></p>")
 .append("<div>")
 .append("<p><font color='red'><strong>Factorial n!</strong></font></p>")
 .append("</div>")
 .append("<p>Calculate: 5!</p>")
 .append("<p>Key in: 5! = &nbsp;Answer: 120</p>")
 .append("<p><font color='red'><strong>Power Functions</strong></font> are enabled by two keys: x<sup>2</sup> (x<sup>3 </sup>is available with longer press on the key x<sup>2</sup>) and y<sup>n</sup>.</p>")
 .append("<p>Calculate: &plusmn;5<sup>2</sup></p>")
 .append("<p><strong>WARNNING</strong></p>")
 .append("<p><span style=\"color: #ff6600;\"><strong>Key in: &plusmn;5<sup>2 </sup>= &nbsp;Answer: 25</strong></font></p>")
 .append("<p><span style=\"color: #ff6600;\"><strong>Key in: -5<sup>2</sup> = &nbsp; Answer: -25</strong></font></p>")
 .append("<p>Calculate: -5<sup>3</sup> and 3<sup>3</sup></p>")
 .append("<p>Key in: -5<sup>3 </sup>= &nbsp;Answer: -125</p>")
 .append("<p>&nbsp;Key in: 3<sup>3</sup> = &nbsp;Answer: 27</p>")
 .append("<p>Calculate: 8<sup>5 </sup>and 6<sup>-1</sup></p>")
 .append("<p>Key in: 8<sup>5</sup> = &nbsp; Answer: 32768</p>")
 .append("<p>Key in: 6<sup>-1</sup> = &nbsp;Answer: 0.166&nbsp;&nbsp;&nbsp;</p>")
 .append("<div>")
 .append("<p><font color='red'><strong>Roots</strong></font></p>")
 .append("</div>")
 .append("<p>Key in: CubicRoot(125) &nbsp;= &nbsp;Answer: 5</p>")
 .append("<p>Calculate: &nbsp;sqrt(25) and</p>")
 .append("<p>Key in: &nbsp;sqrt(25)&nbsp;= &nbsp;Answer: 5</p>")
 .append("<p>Key in: 4-root(625) &nbsp;5 = Answer: 8</p>")
 .append("<p><strong><font color='red'>Trigonometric functions</font>&nbsp;</strong>sin, cos, tan, asin, acos, atan (degrees and radians)</p>")
 .append("<p>Calculate: sin 90 and cos 45</p>")
 .append("<p>Key in: sin 90 = &nbsp;Answer: 1</p>")
 .append("<p>Key in: cos 45 = Answer: 0.7071</p>")
 .append("<p><font color='red'><strong>Logarithmic functions</strong></font> log and ln&nbsp;&nbsp;</p>")
 .append("<p>Calculation: log100 and ln2980.957</p>")
 .append("<p>Key in: log100 = Answer: 2</p>")
 .append("<p>Key in: ln2980.957 = &nbsp;Answer: 8</p>")
 .append("<div>")
 .append("<p><font color='red'><strong>MOD</strong></font></p>")
 .append("</div>")
 .append("<p>Key in: 5MOD3 = &nbsp; Answer: 2</p>")
 .append("<div>")
 .append("<p><span style=\"color: #ff0000; \"><strong>&nbsp;BIN-&gt;OCT-&gt;DEC-&gt;HEX converter</strong></font></p>")
 .append("</div>")
 .append("<p>Key in: DEC-&gt; 10</p>")
 .append("<p>If you wish to Hexadecimal formats press DEC and HEX will appear. The next is BIN (binary system) and then OCT (octal format)</p>")
 .append("<p><font color='red'><strong>The application enables:</strong></font></p>")
 .append("<p>- &nbsp;Revision of calculation and copy from history</p>")
 .append("<p>- &nbsp;Copy and paste the answer on the top of the screen</p>")
 .append("<p>- &nbsp;Convert the measures</p>")
 .append("<p>- &nbsp;Personal placement of keys</p>")
 .append("<p>- &nbsp;Effective assistance to user</p>")
 .append("<p><strong><font color='red'>Graph drawing:</font> </strong>(the key X)</p>")
 .append("<p>- &nbsp;Auto fitting size of area called &lsquo;net&rsquo;&nbsp; in Setting</p>")
 .append("<p>- &nbsp;Conversion among BIN-OCT-HEX</p>")
 .append("<p>- &nbsp;Trigonometric functions (degrees and radians &ndash; select in Setting)</p>")
 .append("<p>- &nbsp;Power functions</p>")
 .append("<p>- &nbsp;Enable digital grouping&nbsp;</p>")
 .append("<p><font color='red'><strong>SET or menu -&gt; Edit</strong></font></p>")
 .append("<p>Personal placement of keys: the key is changed with the press on existing key and then select the new key in a dialogue. Every key has two different modes:</p>")
 .append("<p>1.&nbsp; one normal press</p>")
 .append("<p>2. longer press.</p>")
 .append("<p><font color='red'><strong>History </strong></font></p>")
 .append("<p>It enables the last 10, 20, 30, 40 or 50 notes or results. Press it and it is copied. Paste it in main screen.</p>")
 .append("<p><font color='red'><strong>Settings</strong></font></p>")
 .append("<p>It can be set many things such as angle (IMPORTANT AT DRAWING GRAPH), separation line between thousands, coordinate system with or without the net, enlarge the history.</p>")
 .append("<p><font color='red'><strong>Measure conversion</strong></font></p>")
 .append("<p><font color='red'><strong>SET-&gt;CON </strong></font>(convert units) -&gt;select the unit you want to convert (angle, data, energy, length, mass, power, pressure, speed, surface, temperature, time and volume). Insert the value and select input unit and output unit and the converted value is in the screen.</p>")
 .append("<p><font color='red'><strong>Faq:</strong></font></p>")
 .append("<p>To place the number, select the keys from 0 to 9, decimal and &plusmn;.</p>")
 .append("<p><strong>&lt;-</strong> delete the last enter</p>")
 .append("<p><strong>c</strong>&nbsp; delete all enters</p>")
 .append("<p>press DEC and you are in HEX, press again and system is BIN, again and OCT and the fourth press means we are in DEC (Decimal system) again. If you want to convert the number in other system press the key to the desirable symbol.</p>").toString();
}
